# Generated by Django 5.2.8 on 2025-11-26 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Complaint Subject')),
                ('description', models.TextField(verbose_name='Detailed Issue')),
                ('location', models.CharField(help_text='E.g., Sector 4, Main Market', max_length=200)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='grievances/')),
                ('category', models.CharField(choices=[('ROAD', 'Road & Transport'), ('WATER', 'Water Supply'), ('ELECTRICITY', 'Electricity & Street Lights'), ('GARBAGE', 'Garbage & Cleaning'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
